export const TRANSACTION_TYPES = {
  INCOME: 'income',
  EXPENSE: 'expense'
};

export const TRANSACTION_CATEGORIES = {
  // Income Categories
  RECRUITMENT_FEES: 'recruitment_fees',
  MEDIA_AD_SALES: 'media_ad_sales',
  OUTSOURCING_SERVICES: 'outsourcing_services',
  CV_WRITING_SERVICES: 'cv_writing_services',
  CONSULTING_FEES: 'consulting_fees',
  TRAINING_SERVICES: 'training_services',
  OTHER_INCOME: 'other_income',
  
  // Expense Categories
  OFFICE_RENT: 'office_rent',
  SALARIES_WAGES: 'salaries_wages',
  MARKETING_ADVERTISING: 'marketing_advertising',
  SOFTWARE_SUBSCRIPTIONS: 'software_subscriptions',
  TRAVEL_EXPENSES: 'travel_expenses',
  OFFICE_SUPPLIES: 'office_supplies',
  UTILITIES: 'utilities',
  PROFESSIONAL_SERVICES: 'professional_services',
  EQUIPMENT_PURCHASE: 'equipment_purchase',
  TRAINING_DEVELOPMENT: 'training_development',
  OTHER_EXPENSES: 'other_expenses'
};

export const PAYMENT_METHODS = {
  BANK_TRANSFER: 'bank_transfer',
  CASH: 'cash',
  CHECK: 'check',
  CREDIT_CARD: 'credit_card',
  DEBIT_CARD: 'debit_card',
  PAYPAL: 'paypal',
  STRIPE: 'stripe',
  MOBILE_MONEY: 'mobile_money',
  CRYPTOCURRENCY: 'cryptocurrency',
  OTHER: 'other'
};

export const TRANSACTION_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  PROCESSING: 'processing',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled'
};

export const CATEGORY_LABELS = {
  // Income Categories
  [TRANSACTION_CATEGORIES.RECRUITMENT_FEES]: 'Recruitment Fees',
  [TRANSACTION_CATEGORIES.MEDIA_AD_SALES]: 'Media Ad Sales',
  [TRANSACTION_CATEGORIES.OUTSOURCING_SERVICES]: 'Outsourcing Services',
  [TRANSACTION_CATEGORIES.CV_WRITING_SERVICES]: 'CV Writing Services',
  [TRANSACTION_CATEGORIES.CONSULTING_FEES]: 'Consulting Fees',
  [TRANSACTION_CATEGORIES.TRAINING_SERVICES]: 'Training Services',
  [TRANSACTION_CATEGORIES.OTHER_INCOME]: 'Other Income',
  
  // Expense Categories
  [TRANSACTION_CATEGORIES.OFFICE_RENT]: 'Office Rent',
  [TRANSACTION_CATEGORIES.SALARIES_WAGES]: 'Salaries & Wages',
  [TRANSACTION_CATEGORIES.MARKETING_ADVERTISING]: 'Marketing & Advertising',
  [TRANSACTION_CATEGORIES.SOFTWARE_SUBSCRIPTIONS]: 'Software Subscriptions',
  [TRANSACTION_CATEGORIES.TRAVEL_EXPENSES]: 'Travel Expenses',
  [TRANSACTION_CATEGORIES.OFFICE_SUPPLIES]: 'Office Supplies',
  [TRANSACTION_CATEGORIES.UTILITIES]: 'Utilities',
  [TRANSACTION_CATEGORIES.PROFESSIONAL_SERVICES]: 'Professional Services',
  [TRANSACTION_CATEGORIES.EQUIPMENT_PURCHASE]: 'Equipment Purchase',
  [TRANSACTION_CATEGORIES.TRAINING_DEVELOPMENT]: 'Training & Development',
  [TRANSACTION_CATEGORIES.OTHER_EXPENSES]: 'Other Expenses'
};

export const PAYMENT_METHOD_LABELS = {
  [PAYMENT_METHODS.BANK_TRANSFER]: 'Bank Transfer',
  [PAYMENT_METHODS.CASH]: 'Cash',
  [PAYMENT_METHODS.CHECK]: 'Check',
  [PAYMENT_METHODS.CREDIT_CARD]: 'Credit Card',
  [PAYMENT_METHODS.DEBIT_CARD]: 'Debit Card',
  [PAYMENT_METHODS.PAYPAL]: 'PayPal',
  [PAYMENT_METHODS.STRIPE]: 'Stripe',
  [PAYMENT_METHODS.MOBILE_MONEY]: 'Mobile Money',
  [PAYMENT_METHODS.CRYPTOCURRENCY]: 'Cryptocurrency',
  [PAYMENT_METHODS.OTHER]: 'Other'
};

export const STATUS_LABELS = {
  [TRANSACTION_STATUS.PENDING]: 'Pending',
  [TRANSACTION_STATUS.APPROVED]: 'Approved',
  [TRANSACTION_STATUS.REJECTED]: 'Rejected',
  [TRANSACTION_STATUS.PROCESSING]: 'Processing',
  [TRANSACTION_STATUS.COMPLETED]: 'Completed',
  [TRANSACTION_STATUS.CANCELLED]: 'Cancelled'
};

export const INCOME_CATEGORIES = [
  TRANSACTION_CATEGORIES.RECRUITMENT_FEES,
  TRANSACTION_CATEGORIES.MEDIA_AD_SALES,
  TRANSACTION_CATEGORIES.OUTSOURCING_SERVICES,
  TRANSACTION_CATEGORIES.CV_WRITING_SERVICES,
  TRANSACTION_CATEGORIES.CONSULTING_FEES,
  TRANSACTION_CATEGORIES.TRAINING_SERVICES,
  TRANSACTION_CATEGORIES.OTHER_INCOME
];

export const EXPENSE_CATEGORIES = [
  TRANSACTION_CATEGORIES.OFFICE_RENT,
  TRANSACTION_CATEGORIES.SALARIES_WAGES,
  TRANSACTION_CATEGORIES.MARKETING_ADVERTISING,
  TRANSACTION_CATEGORIES.SOFTWARE_SUBSCRIPTIONS,
  TRANSACTION_CATEGORIES.TRAVEL_EXPENSES,
  TRANSACTION_CATEGORIES.OFFICE_SUPPLIES,
  TRANSACTION_CATEGORIES.UTILITIES,
  TRANSACTION_CATEGORIES.PROFESSIONAL_SERVICES,
  TRANSACTION_CATEGORIES.EQUIPMENT_PURCHASE,
  TRANSACTION_CATEGORIES.TRAINING_DEVELOPMENT,
  TRANSACTION_CATEGORIES.OTHER_EXPENSES
];